import {
  defaultContainerCronJobDefinition,
  multipleContainerCronJobDefinition,
} from "../cron_job/mod.ts";
import {
  defaultContainerJobDefinition,
  multipleContainerJobDefinition,
} from "../job/mod.ts";
import {
  defaultContainersDeploymentDefinition,
  deploymentWithHpaDefinition,
  deploymentWithHpaHpaDefinition,
  fullDefinedDeploymentDefinition,
} from "../deployment/mod.ts";
import {
  defaultContainersStatefulSetDefinition,
  fullDefinedStatefulSetDefinition,
  statefulSetWithHpaDefinition,
  statefulSetWithHpaHpaDefinition,
} from "../stateful_set/mod.ts";
import {
  fullDefinedPvcDefinition,
  fullDefinedSecondPvcDefinition,
  pvcNotMatchingAnyStsDefinition,
  pvcNotMatchingAnyStsInfo,
} from "../pvc/mod.ts";

export const fullDefinedKoreDefinitions = [
  multipleContainerCronJobDefinition,
  multipleContainerJobDefinition,
  fullDefinedDeploymentDefinition,
  deploymentWithHpaDefinition,
  deploymentWithHpaHpaDefinition,
  fullDefinedStatefulSetDefinition,
  statefulSetWithHpaDefinition,
  statefulSetWithHpaHpaDefinition,
  fullDefinedPvcDefinition, // generated from sts
  fullDefinedSecondPvcDefinition, // generated from sts
  pvcNotMatchingAnyStsDefinition, // not generated by any sts
];

export const defaultKoreDefinitions = [
  defaultContainerCronJobDefinition,
  defaultContainerJobDefinition,
  defaultContainersDeploymentDefinition,
  defaultContainersStatefulSetDefinition,
];

export * from "./kore_info.ts";
