name: Deno CI

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Deno tests
        run: deno test